spring:
  application:
    name: sequence-generator

#  datasource:
#    url: jdbc:mysql://localhost:3306/sequence_generator
#    username: root
#    password: root
  datasource:
    url: jdbc:postgresql://localhost:5432/sequence_generator_db
    username: account_user
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
