spring:
  application:
    name: account-service
    bad_request: 400
    conflict: 409
    ok: 200
    not_found: 404

#  datasource:
#    url: jdbc:mysql://localhost:3306/account_service
#    username: root
#    password: root

  datasource:
    url: jdbc:postgresql://localhost:5432/account_service_db
    username: account_user
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
sequence:
  generator:
    url: http://localhost:8083

server:
  port: 8081
